FROM python:3.11-slim

WORKDIR /app

# Install packages
RUN pip install --no-cache-dir fastapi uvicorn redis requests

# Copy python service ONLY
COPY src/workers/python/python_service/ /app/

EXPOSE 9000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000"]